### ISSUE TITLE
Issues about Local contrastive loss.

### ISSUE THREAD

**Issue by freshjarman** [RyanWangZf/Trial2Vec#2]
Hi, I didn't find the relevant codes of `Local contrastive loss.` in the paper `3.3`. Specifically, I don't know how to implement eq(6-8) (like, how to use SciSpacy and map one entity to its canonical name? I didn't find relevant codes in the project). Could u point it out, thanks~

**Comment by RyanWangZf** [comment]
Hi, thanks for your interest in our work. We do not include the part you mention in this version since it will introduce additional package dependency. We instead take a more straightforward case for training, and it undermines the performance in an acceptable range.

**Comment by freshjarman** [comment]
Thanks for your reply. Could u share the part with me? I am glad to see relevant codes of your interesting work. Thanks 😊



---Original---
From: ***@***.***&gt;
Date: Tue, Dec 6, 2022 23:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [RyanWangZf/Trial2Vec] Issues about Local contrastive loss.(Issue #2)




 
Hi, thanks for your interest in our work. We do not include the part you mention in this version since it will introduce additional package dependency. We instead take a more straightforward case for training, and it undermines the performance in an acceptable range.

**Comment by freshjarman** [comment]
> Hi, thanks for your interest in our work. We do not include the part you mention in this version since it will introduce additional package dependency. We instead take a more straightforward case for training, and it undermines the performance in an acceptable range.

I look forward to seeing that version (relevant codes of `Hierarchical contrastive learning`) if you are free. Thanks for ur reply and interesting work which is of great help~ Here's my e-mail: wangtao98@seu.edu.cn 😊

**Comment by RyanWangZf** [comment]
Sent to your email.

**Comment by asamadan** [comment]
Hi Zifeng, 

I was wondering about the same piece related to the local contrastive loss. really appreciate it if you could make that part of the code available. much appreciated! I have sent you a message to your university email in this regards

Thanks,

**Comment by RyanWangZf** [comment]
> @asamadan 

Has sent to your email.

**Comment by altunumut24** [comment]
Hi Zifeng,

Firstly, congrats for great project. I am also interested with same piece of code. Can you send me too please, Thanks in advance (altunumut13@gmail.com)
